"""property images

Revision ID: 351b802d83ed
Revises: dacb56ff968b
Create Date: 2026-07-19 22:11:00.023878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '351b802d83ed'
down_revision: Union[str, None] = 'dacb56ff968b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_images',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('stored_name', sa.String(length=128), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('alt', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name', name='uq_property_image_file')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_images')
    # ### end Alembic commands ###
